### ISSUE TITLE
[CITE-Forum] WCS 1.0.0 r9 test issue

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-wcs10#13]
http://lists.opengeospatial.org/pipermail/cite-forum/2014-December/001431.html

**Comment by dbretschneider** [comment]
As far as I know, the test contains two request against the service:
 * ```DescribeCoverage``` and
 * ```GetCoverage```

The DescribeCoverage request is needed for getting crs and other information. These information where used in the GetCoverage request.

**Comment by segoerke** [comment]
I think the issue here is the following:
The test case sends a DescribeCoverage to identify some of the request parameters for the GetCoverage request. However, even for the XML testcase, the DescribeCoverage request is done with the GET-KVP method. IMHO an implementer can choose either to implement one of HTTP GET and HTTP POST or both.
If a server does not implement HTTP GET for DescribeCoverage it is very likely that the test aborts after unsuccessfully requesting a DescribeCoverage that way und throws an exception.

**Comment by segoerke** [comment]
The very likely solution of the issue is to change the DescribeCoverage Request part for that test to the HTTP POST method.

**Comment by segoerke** [comment]
@dbretschneider

**Comment by dbretschneider** [comment]
I have replaced the DescribeCoverage HTTP GET request with HTTP POST (*not tested by me*) in Pull Request https://github.com/opengeospatial/ets-wcs10/pull/14.
