### ISSUE TITLE
WCS 1.0.0 compliance tests with time-period incorrectly missed a bbox parameter in web requests (te2 v1.18)

### ISSUE THREAD

**Issue by greatzzk** [opengeospatial/ets-wcs10#62]
![image](https://github.com/opengeospatial/ets-wcs10/assets/11200872/fc926c68-9a5c-4d62-bb7f-23c2fbbab1ff)
they are fail with the same problem that the compliance tests don't have a bbox parameter in web request.

e.g. 
![image](https://github.com/opengeospatial/ets-wcs10/assets/11200872/29ba5440-95bd-438b-9c4f-23f3b943eff4)

**Comment by dstenger** [comment]
@greatzzk Thank you for reporting. Did you test on the Production (https://cite.ogc.org/teamengine/) or Beta (https://cite.ogc.org/te2/) environment?
However, the BBOX parameter is not mandatory. Either parameter BBOX or TIME must be present in the request. This test uses the parameter TIME instead of BBOX. Can you please check this?

**Comment by greatzzk** [comment]
@dstenger ok. i think i found a relevant section in 1.0.0 specification stating "A GetCoverage request must include a valid BBOX, or TIME (below), or both."
what should be a server's designed behavior when a request has time but doesn't have a bbox. should we just use the full service's extent?

**Comment by dstenger** [comment]
Yes, that is correct.
Do you have any further questions? If not, can you please close this issue?
